/* BANCO DE DADOS NORMALIZADO, DE FORMA QUE UM USUARIO SÓ POSSA TER 
UM ENDERECO ASSOCIADO A ELE*/ 

CREATE DATABASE BDVALIDADADOS;

USE BDVALIDADADOS;

CREATE TABLE ENDERECO(
    CODENDERECO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RUA VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(70) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    UF CHAR(02) NOT NULL,
    CEP CHAR(8) NOT NULL
);
CREATE TABLE USUARIO(
    CODUSUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    NUMERO INT,
    COMPLEMENTO VARCHAR(100),
    CODENDERECO INT NOT NULL,
    CONSTRAINT FKEND FOREIGN KEY(CODENDERECO) 
    REFERENCES ENDERECO(CODENDERECO)
)

  
  
    
    
    